---
steps:

  publish-snapshot:
    image: eclipse-temurin:21
    commands:
      - ./gradlew publish -Pbranch=$CI_COMMIT_BRANCH -PossrhUsername=$OSSRH_USER -PossrhPassword=$OSSRH_PASSWORD
    secrets: [ ossrh_user, ossrh_password]
    when:
      event: push

  publish-release:
    image: eclipse-temurin:21
    commands:
      #- ./gradlew publish -Prelease=true -PossrhUsername=$OSSRH_USER -PossrhPassword=$OSSRH_PASSWORD
      - echo "needs gpg key, has to be done locally for now"
      - exit 1
    secrets: [ ossrh_user, ossrh_password]
    when:
      event: tag

  